### ISSUE TITLE
NSCocoaErrorDomain Code=258

### ISSUE THREAD

**Issue by bernhardwaidacher** [ashqal/MD360Player4iOS#1]
Hi!

I'm using  Swift in my project. And I get the following error using this code:
`2016-04-20 16:30:36.190 Eagle[11928:637852] ERROR while loading from file: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."
2016-04-20 16:30:36.191 Eagle[11928:637852] ERROR while loading from file: Error Domain=NSCocoaErrorDomain Code=258 "The file name is invalid."`

`                    let playerItem = AVPlayerItem(URL: "http://d8d913s460fub.cloudfront.net/krpanocloud/video/airpano/video-1920x960a.mp4")
                    let player = AVPlayer(playerItem: playerItem)

                    let playerController = AVPlayerViewController()
                    
                    playerController.player = player
                    
                    playerController.modalPresentationStyle = UIModalPresentationStyle.OverFullScreen
                    self.presentViewController(playerController, animated: true, completion: nil)
                    
                    player.play()
                    
                    let config:MDVRConfiguration = MDVRLibrary.createConfig()
                    
                    config.displayMode(MDModeDisplay.Glass)
                  //  config.interactiveMode(MDMo)
                    
                    config.asVideo(playerItem)
                    config.setContainer(self, view: self.view)
                    
                    let lib = config.build()`

If I uncomment all the code of your framework, it works. 
The program stops working at GLUtil.m at line 254

You know anything I could do?

**Comment by ashqal** [comment]
Sorry, I am not familiar with Swift. But,
1.Make sure using `fileURLWithPath` while play the local file.
```
NSString *path = [[NSBundle mainBundle] pathForResource:@"skyrim360" ofType:@"mp4"];
AVPlayerItem *playerItem = [[AVPlayerItem alloc] initWithURL:[NSURL fileURLWithPath:path]];
```

2.You may retain the `MDVRLibrary` instance to prevent from being auto-released.

**Comment by Erickson0806** [comment]
遇到同样的问题，可能跟swift有关吧
config.build()函数里crash了，GLUtil.m at line 254

**Comment by DavidMorenoDWeb** [comment]
Do you solved this problem? I have the same problem now.

**Comment by bernhardwaidacher** [comment]
No I haven’t worked on the project where I need this since then. I’m sorry

**Comment by DavidMorenoDWeb** [comment]
Ok, thank you. If I find the solution I will post it here.

**Comment by DavidMorenoDWeb** [comment]
I managed to resolve the problem replacing the line 13 in MDVRLibrary.h.

I had to put:

#define MDVR_RAW_NAME @"Frameworks/MD360Player4iOS.framework/vrlibraw.bundle"

Instead of:

#define MDVR_RAW_NAME @"vrlibraw.bundle"

**Comment by ashqal** [comment]
@DavidMorenoDWeb  Thanks a lot!

**Comment by DavidMorenoDWeb** [comment]
Thank you for this library! @ashqal :)

**Comment by maselko** [comment]
Thank you David, 
file: MDVRHeader.h 👍

**Comment by Ohtico** [comment]
where is this file?, I am using react native
