### ISSUE TITLE
3D 180度全景播放，修改了纹理坐标后，显示界面异常，该如何修改呢？

### ISSUE THREAD

**Issue by hd03022163** [ashqal/MD360Player4iOS#13]
你好，我使用了你的sdk来做一个播放器app，播放3D180度的视频，视频源为左右显示的源，我修改了generateSphere中生成的texcoords 部分代码，分屏显示可以看出有3D的效果，但是视频对接的地方会多出一部分异常显示的纹理，一下为我修改的代码，能帮忙看看是那边改错了吗 还是修改思路不正确，谢谢！
//texcoords[t] = s*S;
float curTexcoord = s*S;
            switch (type) {
                case Type3D180:
                    if (bLeft) {
                        texcoords[t] = s< sectors/2?curTexcoord:(s-sectors/2)*S;
                    }
                    else{
                        texcoords[t] = s< sectors/2?(s + sectors/2)*S:curTexcoord;
                    }

                    break;

**Comment by ashqal** [comment]
Will implement soon.

**Comment by ashqal** [comment]
```objc
[config projectionMode:MDModeProjectionStereoSphere];
```
