### ISSUE TITLE
swift版本?

### ISSUE THREAD

**Issue by terenzeyuen** [ashqal/MD360Player4iOS#14]
你的插件非常好！ 请问有没有swift的版本？

**Comment by ashqal** [comment]
抱歉 能力有限 还没学swfit..

**Comment by terenzeyuen** [comment]
Free for some Android freelance projects...?

**Comment by ashqal** [comment]
Of course, under the Apache 2.0 License.

**Comment by ashqal** [comment]
Sorry, there is a lot of work to be done..
