### ISSUE TITLE
The media data could not be decoded on this device

### ISSUE THREAD

**Issue by DavidMorenoDWeb** [ashqal/MD360Player4iOS#15]
Hi!

I have this error only on iPhone 5 and I have no idea for the reason:

Video player Status Failed: player item error = Error Domain=AVFoundationErrorDomain Code=-11855 "Cannot Decode" UserInfo={NSLocalizedDescription=Cannot Decode, NSUnderlyingError=0x17e9cdd0 {Error Domain=NSOSStatusErrorDomain Code=-12910 "(null)"}, NSLocalizedFailureReason=The media data could not be decoded on this device.}
2016-06-16 09:56:01.762 Videos360[236:8930] Video player Status Failed: player error = (null)

This occurs only on iPhone 5 and only with network videos. Anyone had this problem later? Thanks!!

**Comment by ashqal** [comment]
Sorry, it is a error in AVPlayer, not this library.

**Comment by DavidMorenoDWeb** [comment]
Ok, thanks!

**Comment by semenag01** [comment]
@DavidMorenoDWeb  Hi Did you resolve this issue?
