### ISSUE TITLE
YUV Data Support

### ISSUE THREAD

**Issue by Rannie** [ashqal/MD360Player4iOS#2]
Demo use CVPixelBufferRef.How to render YUV originnal frame data?

**Comment by ashqal** [comment]
Not support now, but
[Y-UV](https://github.com/hanton/HTY360Player/blob/master/HTY360Player/HTYGLKVC.m)
[Y-U-V](https://github.com/davidAgo4g/VideoPlayer-iOS/blob/master/ES2Renderer.m)
may help.

**Comment by Rannie** [comment]
thx. also hope to support render 360 with yuv data.

**Comment by ashqal** [comment]
https://github.com/ashqal/MD360Player4iOS/releases/tag/1.1.0

supported!
