### ISSUE TITLE
封装的太乱了,没什么实用性

### ISSUE THREAD

**Issue by iOSSinger** [ashqal/MD360Player4iOS#3]
很好用,按照楼主所说的做就可以了,谢谢楼主

**Comment by ashqal** [comment]
你确定？

**Comment by ashqal** [comment]
不知道你有没有阅读过源代码，`MDVRLibrary `只负责对外提供参数配置，内部完成渲染。播放器相关的播放、播放控制都交给用户自己实现。渲染与播放器之间的耦合只有一个AVPlayerItem。还有比这更简单的封装？

**Comment by iOSSinger** [comment]
嗯,首先我真诚的跟您道个歉,我太鲁莽了,应该尊重您的劳动成果.你代码确实不错,比HTY360Player要好很多.功能也很强大.
