### ISSUE TITLE
Question iOS - Android 

### ISSUE THREAD

**Issue by matejvida** [ashqal/MD360Player4iOS#31]
This a a question rather than an issue. Are there big differences between the two libraries? I have been following both repositories and it seems that Android is getting the whole attention, does that mean that iOS is good enough and Android needs more work?

**Comment by ashqal** [comment]
Because I am an Android developer, and more familiar with java...

**Comment by matejvida** [comment]
Same here :) Great work BTW!

**Comment by ashqal** [comment]
@matejvida 😄
