### ISSUE TITLE
使用最新的ijkplayer播放器 版本 开启glass模式后 屏幕不是对称分割的

### ISSUE THREAD

**Issue by iOS-mamu** [ashqal/MD360Player4iOS#33]
Dear 楼主:

使用最新的ijk播放器版本 能够正常播放，但是使用glass模式后(就是屏幕分两半，带眼睛)，不是对称的，左半边屏幕比右半边的屏幕宽。

**Comment by ashqal** [comment]
算错屏幕大小了，自己修改一下就好了

**Comment by d6638219** [comment]
怎么修改，改哪里的代码
