### ISSUE TITLE
真机运行有几率黑屏?

### ISSUE THREAD

**Issue by heshanghuixitou123** [ashqal/MD360Player4iOS#5]
在真机上运行时有几率会黑屏, 大概20%几率的样子, 求解怎么办?

**Comment by ashqal** [comment]
可能是播放器问题，可以麻烦定位下问题原因吗？

**Comment by heshanghuixitou123** [comment]
在模拟器上没问题, 就是在真机运行时有时会黑屏, 并不崩溃, 有声音没画面, 视频也在走.

**Comment by ashqal** [comment]
那就是库的问题了 我回去试试

**Comment by heshanghuixitou123** [comment]
恩 如果找到原因麻烦告诉我下 多谢了

**Comment by ashqal** [comment]
客气哈，感谢反馈
解决了我会过来close issue的，你应该会收到邮件推送

**Comment by heshanghuixitou123** [comment]
在真机上加载网络视频的时候不黑屏, 播放本地视频的时候第一次进去黑屏, 之后返回再进就都黑屏了

**Comment by ashqal** [comment]
在播放器界面锁屏后，第二次打开准是黑的

**Comment by heshanghuixitou123** [comment]
怎么触发的界面锁屏啊, 能不能避免使它不会黑屏?

**Comment by ashqal** [comment]
按power键锁屏....
避免黑屏肯定不是根治的办法 能复现问题后面就好排查了

**Comment by heshanghuixitou123** [comment]
没有锁屏也会黑屏啊 黑屏的几率也不稳定, 有时候基本不黑屏, 有时候次次都是黑屏...

**Comment by ashqal** [comment]
估计是同一个原因，锁屏后比较好复现

**Comment by ashqal** [comment]
调用`MDVideoDataAdatperAVPlayerImpl#copyPixelBuffer`有一定几率返回nil，

http://stackoverflow.com/questions/33036609/copypixelbufferforitemtimeitemtimefordisplay-null-value

**Comment by heshanghuixitou123** [comment]
经过修改之后, 黑屏几率大大降低了, 不过有时候还是会黑屏一两次 还没有找到复现的条件...

**Comment by gqf2008** [comment]
我这里发现横屏切换到竖屏时黑屏，视频还在播放，不知道是不是同样的原因引起的

**Comment by mydy1987** [comment]
目前还是会黑屏，测试了下20次里，有6次黑屏。

**Comment by Jasoncoool** [comment]
这个是不是播放器的问题额,我自己更换了播放器,没有黑屏的问题

**Comment by ashqal** [comment]
@Jasoncoool 使用的是哪个播放器？demo里用的是avplayer

**Comment by Jasoncoool** [comment]
用的zfplayer  也是AVplayer封装的  细节上可能处理了一下  另外我们都是流媒体文件不知道和这有没有关系

**Comment by AdvanceYe** [comment]
- (UIInterfaceOrientationMask)supportedInterfaceOrientations;
如果通过这个方法把第一个页面如果设置成竖屏的，player vc设置为横屏的，那么点击了local file的play之后，大概80%概率变成黑屏的说。

**Comment by AdvanceYe** [comment]
不要用VIMVideoPlayerView和VIMVideoPlayer，initPlayer的时候直接用原生的AVPlayer和AVPlayerItem替代。所有的黑屏bug都消失了~
ps.另外还改了下这里，不知道是否也起到作用了：
`- (void)launch:(NSURL*)url {
    
    UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Player" bundle:nil];
    PlayerViewController *vc = [storyboard instantiateViewControllerWithIdentifier:@"PlayerViewController"];
    vc.videoURL = url;
    [vc initParams:url];//移至此处
    
    [self presentViewController:vc animated:YES completion:^{
        //        [vc initParams:url];//移出去
    }];
}`

**Comment by ashqal** [comment]
@AdvanceYe 感谢 回去试试

**Comment by AdvanceYe** [comment]
@ashqal 不客气~您试试:)

**Comment by liuning1084126465** [comment]
最新版本的无法启动，缺少SDWebImage?

**Comment by liuning1084126465** [comment]
黑屏问题解决了吗？

**Comment by ashqal** [comment]
麻烦各位测试下，我试了100次 都是ok的
