### ISSUE TITLE
Missing barrel distortion filter

### ISSUE THREAD

**Issue by davibe** [ashqal/MD360Player4iOS#68]
For a correct VR experience I think Barrel distortion filter is a must. It's present in the Android version of the library but I could not find one on the iOS library. Is it an already planned feature ?

**Comment by davibe** [comment]
please ? an answer ?

**Comment by ashqal** [comment]
I had commit it to my local branch, and will push it in this week.

**Comment by davibe** [comment]
I have seen the commit and just quickly tested it. It seems to be working just fine. Thank you, big times.
