### ISSUE TITLE
页面触发viewWillDisappear时会自动停止画面渲染

### ISSUE THREAD

**Issue by lvXiaoPeng** [ashqal/MD360Player4iOS#72]
如果在播放过程中拖动当前页面会发现视频有声音播放，但是画面是停止的，在停止拖动后画面继续渲染，请问这个是在哪里可以更改

**Comment by ashqal** [comment]
这个可能是GLKView有关

**Comment by lvXiaoPeng** [comment]
我试了注释掉MD360PlayerMode这个宏使用IJKPlayer的渲染和我自定义的GLKViewController进行渲染都是没问题的，目前还没有找到什么原因

**Comment by lvXiaoPeng** [comment]
在MDGLKViewController添加viewWillDisappear方法，在此时将self.paused设置为NO即可解决这个问题，在整个工程里没有找到有地方主动将paused设置为yes的
