### ISSUE TITLE
可以播放全景图吗

### ISSUE THREAD

**Issue by MeiMen** [ashqal/MD360Player4iOS#8]

**Comment by ashqal** [comment]
预留了，还没封装进去，所以现在还不行

**Comment by MeiMen** [comment]
哦，什么时候回封装进去呢

**Comment by ashqal** [comment]
这个难度不大 我预计本周内吧

**Comment by MeiMen** [comment]
太好了，会支持哪些功能呢，可以自由设置热点进行漫游吗。我很努力在学习你的代码，不过还看不太懂。

**Comment by Rannie** [comment]
请问怎么将 uiimage -> yuv cvpixelbufferref

**Comment by ashqal** [comment]
@Rannie 我视频方面的积累不是很多，但是感觉google一下uiimage(RGB)转yuv应该会有人做过

**Comment by Rannie** [comment]
另外还有一个问题 就是在开陀螺仪的情况下同时支持手势拖动~

**Comment by ashqal** [comment]
@Rannie 建议增加一个`MDInteractiveStrategy`，然后把`MDTouchStrategy `和`MDMotionStrategy `两个实现抄进去就可以了

**Comment by Rannie** [comment]
嗯 有机会多看下你源码 我最近也在打算开源一个全景视频显示的仓库 基于 HTY 那个修复了他转动和内存泄露的 bug 也想多跟你沟通下 方便留下联系方式吗？

**Comment by ashqal** [comment]
![image](https://cloud.githubusercontent.com/assets/5126517/15381968/5a0e56a2-1db7-11e6-986e-462d96dd5e02.jpeg)

刚建了qq群 欢迎加入

**Comment by ashqal** [comment]
这个功能我本地已经做完了 但是发现了其他地方引起的一个崩溃 所以还没提交 等修复了这个崩溃后再一起push

**Comment by SanPanG-K** [comment]
播放全景图 封装进去了么

**Comment by ashqal** [comment]
@SanPanG-K 那个crash问题一直困扰着我 还是没有解决

图片的有push到分支上，但是图片是倒着的，我一直想等crash解决了再去继续做新功能，所以抱歉这个功能还不完善

**Comment by ashqal** [comment]
fixed!
