### ISSUE TITLE
莫名其妙 黑屏

### ISSUE THREAD

**Issue by gityoung** [ashqal/MD360Player4iOS#9]
- (void)viewDidLoad {
    [super viewDidLoad];
    self.view.backgroundColor = [UIColor whiteColor];
    
    self.url = @"http://125.39.35.137/mp4files/301700000831C244/d8d913s460fub.cloudfront.net/krpanocloud/video/airpano/video-1920x960a.mp4";
    
    self.playerView = [[VIMVideoPlayerView alloc] initWithFrame:CGRectMake(0, 0, [[UIScreen mainScreen] bounds].size.width, [[UIScreen mainScreen] bounds].size.height)];
    [self.playerView setVideoFillMode:AVLayerVideoGravityResizeAspect];
    AVPlayerItem *playerItem = [[AVPlayerItem alloc] initWithURL:[NSURL URLWithString:self.url]];
    [self.playerView.player setPlayerItem:playerItem];
    [self.playerView.player play];
    
    
    MDVRConfiguration* config = [MDVRLibrary createConfig];
    
    [config displayMode:MDModeDisplayNormal];
    [config interactiveMode:MDModeInteractiveMotion];
    [config asVideo:playerItem];
    [config setContainer:self view:self.view];
    
    self.parseVideo = [config build];
}

开始可以播放 ，后来加了个切换MODE的button  ，过了几次黑屏了，去了button也不管用

**Comment by heshanghuixitou123** [comment]
和你加这个button没关系, 黑屏的原因目前不知道, 这个库和HTY那个库都有黑屏的问题, 而且都是随机黑屏的, 不知道怎么解决...

**Comment by ashqal** [comment]
#5 和这个问题一样，`MDVideoDataAdatperAVPlayerImpl#copyPixelBuffer`有一定几率返回nil
